### ISSUE TITLE
[flutter_web] showToastWidget crashes in release mode on flutter web

### ISSUE THREAD

**Issue by shashwatadi** [OpenFlutter/flutter_oktoast#66]
It works fine in debug mode or with --verbose, but breaks when ran using --release or in production.

Error: ` Another exception was thrown: Instance of 'minified:hH<void>' `

`flutter run -d chrome --release --verbose`
```
[ +153 ms] executing: [/Users/shashwataditya/tools/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 916c3ac648aa0498a70f32b5fc4f6c51447628e3
[        ] executing: [/Users/shashwataditya/tools/flutter/] git tag --contains HEAD
[ +458 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.0
           1.20.0-7.4.pre
           1.20.1
           1.20.2
[  +15 ms] executing: [/Users/shashwataditya/tools/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [/Users/shashwataditya/tools/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +82 ms] executing: [/Users/shashwataditya/tools/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +11 ms] executing: sw_vers -productName
[  +25 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 10.13.6
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[   +1 ms] 17G13035
[  +53 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] executing: /Users/shashwataditya/Library/Android/sdk/platform-tools/adb devices -l
[  +24 ms] executing: /usr/bin/xcode-select --print-path
[  +12 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[   +1 ms] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[+1103 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 10.1
           Build version 10B61
[   +1 ms] Xcode not found. Run 'flutter doctor' for more information.
[  +49 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +184 ms] Found plugin cloud_firestore at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/
[  +15 ms] Found plugin cloud_firestore_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+1/
[  +27 ms] Found plugin firebase_analytics at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-6.0.0/
[   +4 ms] Found plugin firebase_analytics_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[   +2 ms] Found plugin firebase_auth at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.0+1/
[   +6 ms] Found plugin firebase_auth_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.0+1/
[   +2 ms] Found plugin firebase_core at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0/
[   +4 ms] Found plugin firebase_core_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[   +7 ms] Found plugin flutter_custom_tabs at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_custom_tabs-0.6.0/
[  +11 ms] Found plugin flutter_plugin_android_lifecycle at
/Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.8/
[  +19 ms] Found plugin google_sign_in at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.1/
[   +4 ms] Found plugin google_sign_in_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1+1/
[  +28 ms] Found plugin image_picker at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+4/
[  +41 ms] Found plugin path_provider at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11/
[   +1 ms] Found plugin path_provider_linux at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[   +3 ms] Found plugin path_provider_macos at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[  +23 ms] Found plugin social_share at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/social_share-2.0.5/
[  +35 ms] Found plugin url_launcher at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/
[   +1 ms] Found plugin url_launcher_linux at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+1/
[   +1 ms] Found plugin url_launcher_macos at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+7/
[   +2 ms] Found plugin url_launcher_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.2/
[  +73 ms] Found plugin cloud_firestore at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/
[   +2 ms] Found plugin cloud_firestore_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+1/
[  +12 ms] Found plugin firebase_analytics at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-6.0.0/
[   +1 ms] Found plugin firebase_analytics_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[   +1 ms] Found plugin firebase_auth at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.0+1/
[   +1 ms] Found plugin firebase_auth_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.0+1/
[   +1 ms] Found plugin firebase_core at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0/
[   +1 ms] Found plugin firebase_core_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[   +1 ms] Found plugin flutter_custom_tabs at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_custom_tabs-0.6.0/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at
/Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.8/
[   +8 ms] Found plugin google_sign_in at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.1/
[   +3 ms] Found plugin google_sign_in_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1+1/
[   +4 ms] Found plugin image_picker at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+4/
[   +9 ms] Found plugin path_provider at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11/
[        ] Found plugin path_provider_linux at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[   +1 ms] Found plugin path_provider_macos at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[  +12 ms] Found plugin social_share at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/social_share-2.0.5/
[   +7 ms] Found plugin url_launcher at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/
[   +4 ms] Found plugin url_launcher_linux at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+1/
[   +1 ms] Found plugin url_launcher_macos at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+7/
[   +1 ms] Found plugin url_launcher_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.2/
[  +76 ms] Generating /Users/shashwataditya/flutter/Kohbee/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +268 ms] Launching lib/main.dart on Chrome in release mode...
[  +64 ms] Found plugin cloud_firestore at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/
[   +1 ms] Found plugin cloud_firestore_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+1/
[   +8 ms] Found plugin firebase_analytics at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-6.0.0/
[   +1 ms] Found plugin firebase_analytics_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[        ] Found plugin firebase_auth at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.0+1/
[   +1 ms] Found plugin firebase_auth_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.0+1/
[   +3 ms] Found plugin firebase_core at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0/
[   +1 ms] Found plugin firebase_core_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[   +1 ms] Found plugin flutter_custom_tabs at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_custom_tabs-0.6.0/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at
/Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.8/
[   +2 ms] Found plugin google_sign_in at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.1/
[        ] Found plugin google_sign_in_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1+1/
[   +2 ms] Found plugin image_picker at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+4/
[  +11 ms] Found plugin path_provider at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11/
[        ] Found plugin path_provider_linux at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[        ] Found plugin path_provider_macos at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[   +4 ms] Found plugin social_share at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/social_share-2.0.5/
[  +10 ms] Found plugin url_launcher at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/
[        ] Found plugin url_launcher_linux at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+1/
[        ] Found plugin url_launcher_macos at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+7/
[        ] Found plugin url_launcher_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.2/
[  +35 ms] Found plugin cloud_firestore at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.0+2/
[   +1 ms] Found plugin cloud_firestore_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+1/
[   +4 ms] Found plugin firebase_analytics at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-6.0.0/
[   +1 ms] Found plugin firebase_analytics_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.1.1/
[        ] Found plugin firebase_auth at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.0+1/
[   +1 ms] Found plugin firebase_auth_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.0+1/
[        ] Found plugin firebase_core at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0/
[   +2 ms] Found plugin firebase_core_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[   +2 ms] Found plugin flutter_custom_tabs at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_custom_tabs-0.6.0/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at
/Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.8/
[   +2 ms] Found plugin google_sign_in at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.1/
[        ] Found plugin google_sign_in_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1+1/
[   +6 ms] Found plugin image_picker at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.7+4/
[   +7 ms] Found plugin path_provider at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11/
[        ] Found plugin path_provider_linux at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[   +1 ms] Found plugin path_provider_macos at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[   +9 ms] Found plugin social_share at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/social_share-2.0.5/
[   +6 ms] Found plugin url_launcher at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.0/
[        ] Found plugin url_launcher_linux at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+1/
[        ] Found plugin url_launcher_macos at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+7/
[   +1 ms] Found plugin url_launcher_web at /Users/shashwataditya/tools/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.2/
[  +24 ms] Generating /Users/shashwataditya/flutter/Kohbee/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +7 ms] Compiling lib/main.dart for the Web...
[  +19 ms] Initializing file store
[   +9 ms] Done initializing file store
[  +81 ms] Skipping target: gen_localizations
[  +19 ms] Skipping target: web_entrypoint
[ +846 ms] dart2js: Starting due to {InvalidatedReason.inputChanged}
[+40432 ms] dart2js: Complete
[  +68 ms] invalidated build due to missing files: /Users/shashwataditya/flutter/Kohbee/DOES_NOT_EXIST_RERUN_FOR_WILDCARD865199376
[ +123 ms] web_release_bundle: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.inputMissing}
[ +277 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[ +188 ms] web_release_bundle: Complete
[ +256 ms] Skipping target: web_service_worker
[   +2 ms] Persisting file store
[  +10 ms] Done persisting file store
[  +29 ms] Compiling lib/main.dart for the Web... (completed in 42.3s)
[ +957 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:63801/devtools/browser/25ad54c5-83ba-41d4-8d30-9590ed3331fe
[+1008 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +5 ms] For a more detailed help message, press "h". To quit, press "q".
```

`pubspec.yaml`
```
name: Kohbee
description: Live classes for CBSE, ICSE

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  firebase_auth: any #^0.16.1
  google_sign_in: ^4.5.1
  http: ^0.12.1
  moor: ^3.1.0
  flare_flutter: ^2.0.1
  google_fonts: ^1.1.0
  curved_navigation_bar: ^0.3.3
  get_it: ^4.0.2
  intl: ^0.16.1
  xml: ^4.2.0
  crypto: ^2.1.5
  url_launcher: ^5.5.0
  stacked: ^1.7.4
  uuid: ^2.2.0
  universal_html: ^1.2.1
  oktoast: ^2.3.2
  platform_detect: ^1.4.0
  flutter_slidable: ^0.5.5
  flutter_launcher_icons: ^0.7.5
  flutter_custom_tabs: ^0.6.0
  dash_chat: ^1.1.14
  firebase: ^7.3.0
  cloud_firestore:
  # firebase_storage: ^3.1.6
  image_picker: ^0.6.7+4
  timeago: ^2.0.26
  social_share: ^2.0.5
  grouped_list: ^3.3.0
  logger: ^0.6.0
  firebase_analytics: ^6.0.0
  flutter_spinkit: ^4.1.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.1.0
  build_runner: ^1.10.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/Icon-192.png"
  image_path_ios: "assets/icons/apple-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.13.6 17G13035, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```
